print("LISTMETHODS")
print("%%%%%%%Append%%%%%%")
x=[1,-2,"vaishu",4.4,9]
x.append("python")
print(x)
print("////////////")
print("%%%%%Extend%%%%%%")
x.extend([10,77,999,000])
print(x)
print("//////////")
print("%%%%Count%%%%%%")
v=[1,2,3]
print(v.count(1))
print("//////////")
print("%%%%Remove%%%%%%")
v.remove(1)
print(v)
print("//////////")
print("%%%%POP%%%%%%")
z=[1,2,3]
z.pop(0)
print(z)
print("//////////")
print("%%%%Index%%%%%%")
i=[1,2,3]
print(i.index(2))
print("//////////")
print("%%%%Changing Elements%%%%%%")
c=[1,2,3]
c[1]=99
print("//////////")
print("%%%%Insert%%%%%%")
lst = [1, 2, 3]
lst.insert(1, 10)
print(lst)
print("//////////")
print("%%%%ForLoop%%%%%%")
for l in [1,2,3,"vaishu"]:
       print(l) 
print("//////////")
print("%%%%Length%%%%%%")
L = [10, 20, 30]
print(len(L))
print("//////////")
print("%%%%Sort%%%%%%")
s = [5, 2, 9, 1]
s.sort()
print(s)
print("//////////")
print("%%%%Clear%%%%")
r = [1, 2, 3]
r.clear()
print(r)
 