print("LIST REMOVE")
FRUITS=["APPLE","BANANA","CHERRY"]
FRUITS.remove("BANANA")
print(FRUITS)
FRUITS=["APPLE","BANANA","CHERRY"]
FRUITS.pop(0)
print(FRUITS)
FRUITS=["APPLE","BANANA","CHERRY"]
FRUITS.pop()
print(FRUITS)

