print("DATA TYPES")
a="HELLOWORLD"#str
print(a)
b=10#int
print(b)
c=20.5#float
print(c)
d=1j#complex
print(d)
e=[1,2,3]#list
print(e)
f=(1,2,3)#tuple
print(f)
g={1}#set
print(g)
h=range(5)
print(h)
i={"vaishu","Reddy"}#DICT
print(i)
j=False#bool
print(j)
k=bytearray(5)#BYTEARRAY
print(k)
l=frozenset({"vaishu","Reddy"})#FROZENSET
print(l)
m=memoryview(bytes(5))#MEMORYVIEW
print(m)
n=None#NONETYPE
print(n)



