print("List Datatype")
#LIST IS THE BUILT IN DATA TYPE IN PYTHON TO STORE COLLECTION OF DATA.
"""
LIST IS
>ORDERED
>CHANGEABLE
>ALLOW DUPLICATE VALUES
>AND ALSO INDEXED
"""
PHONES=["SAMSUNG","IPHONE","REDMI",3]
print(PHONES)